language: csharp
solution: logrotate.sln

install:
  - nuget restore logrotate.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release logrotate.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./tests/logrotatewin.tests/bin/Release/logrotatewin.tests.dll