// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace logrotate {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("logrotate.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LookingForFolders {
            get {
                return ResourceManager.GetString("LookingForFolders", resourceCulture);
            }
        }
        
        internal static string ForceOptionRotate {
            get {
                return ResourceManager.GetString("ForceOptionRotate", resourceCulture);
            }
        }
        
        internal static string UnknownDirective {
            get {
                return ResourceManager.GetString("UnknownDirective", resourceCulture);
            }
        }
        
        internal static string ExecutingPostRotateSharedScripts {
            get {
                return ResourceManager.GetString("ExecutingPostRotateSharedScripts", resourceCulture);
            }
        }
        
        internal static string WithWildcardPattern {
            get {
                return ResourceManager.GetString("WithWildcardPattern", resourceCulture);
            }
        }
        
        internal static string AddingConfigFile {
            get {
                return ResourceManager.GetString("AddingConfigFile", resourceCulture);
            }
        }
        
        internal static string VerboseOptionSet {
            get {
                return ResourceManager.GetString("VerboseOptionSet", resourceCulture);
            }
        }
        
        internal static string Matching {
            get {
                return ResourceManager.GetString("Matching", resourceCulture);
            }
        }
        
        internal static string LogFileEmpty {
            get {
                return ResourceManager.GetString("LogFileEmpty", resourceCulture);
            }
        }
        
        internal static string RotateSimulated {
            get {
                return ResourceManager.GetString("RotateSimulated", resourceCulture);
            }
        }
        
        internal static string ExecutingLastAction {
            get {
                return ResourceManager.GetString("ExecutingLastAction", resourceCulture);
            }
        }
        
        internal static string MailOptionSet {
            get {
                return ResourceManager.GetString("MailOptionSet", resourceCulture);
            }
        }
        
        internal static string Compressing {
            get {
                return ResourceManager.GetString("Compressing", resourceCulture);
            }
        }
        
        internal static string ShreddingFile {
            get {
                return ResourceManager.GetString("ShreddingFile", resourceCulture);
            }
        }
        
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        internal static string Executing {
            get {
                return ResourceManager.GetString("Executing", resourceCulture);
            }
        }
        
        internal static string UpdateStatus {
            get {
                return ResourceManager.GetString("UpdateStatus", resourceCulture);
            }
        }
        
        internal static string CreateNewEmptyLogFile {
            get {
                return ResourceManager.GetString("CreateNewEmptyLogFile", resourceCulture);
            }
        }
        
        internal static string ProcessInclude {
            get {
                return ResourceManager.GetString("ProcessInclude", resourceCulture);
            }
        }
        
        internal static string Usage1 {
            get {
                return ResourceManager.GetString("Usage1", resourceCulture);
            }
        }
        
        internal static string Usage2 {
            get {
                return ResourceManager.GetString("Usage2", resourceCulture);
            }
        }
        
        internal static string Usage3 {
            get {
                return ResourceManager.GetString("Usage3", resourceCulture);
            }
        }
        
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        internal static string UnknownSizeType {
            get {
                return ResourceManager.GetString("UnknownSizeType", resourceCulture);
            }
        }
        
        internal static string Renaming {
            get {
                return ResourceManager.GetString("Renaming", resourceCulture);
            }
        }
        
        internal static string NoFilesFound {
            get {
                return ResourceManager.GetString("NoFilesFound", resourceCulture);
            }
        }
        
        internal static string RotatingFile {
            get {
                return ResourceManager.GetString("RotatingFile", resourceCulture);
            }
        }
        
        internal static string CouldNotBeFound {
            get {
                return ResourceManager.GetString("CouldNotBeFound", resourceCulture);
            }
        }
        
        internal static string Skipping {
            get {
                return ResourceManager.GetString("Skipping", resourceCulture);
            }
        }
        
        internal static string ExecutingPreRotateSharedScripts {
            get {
                return ResourceManager.GetString("ExecutingPreRotateSharedScripts", resourceCulture);
            }
        }
        
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        internal static string GlobalOptionsAboveSections {
            get {
                return ResourceManager.GetString("GlobalOptionsAboveSections", resourceCulture);
            }
        }
        
        internal static string MatchedFolder {
            get {
                return ResourceManager.GetString("MatchedFolder", resourceCulture);
            }
        }
        
        internal static string ExtInTaboo {
            get {
                return ResourceManager.GetString("ExtInTaboo", resourceCulture);
            }
        }
        
        internal static string TruncateLogFile {
            get {
                return ResourceManager.GetString("TruncateLogFile", resourceCulture);
            }
        }
        
        internal static string ExecutingFirstAction {
            get {
                return ResourceManager.GetString("ExecutingFirstAction", resourceCulture);
            }
        }
        
        internal static string ReadLine {
            get {
                return ResourceManager.GetString("ReadLine", resourceCulture);
            }
        }
        
        internal static string ForceOptionSet {
            get {
                return ResourceManager.GetString("ForceOptionSet", resourceCulture);
            }
        }
        
        internal static string RotateBasedonFileSize {
            get {
                return ResourceManager.GetString("RotateBasedonFileSize", resourceCulture);
            }
        }
        
        internal static string UnknownCmdLineArg {
            get {
                return ResourceManager.GetString("UnknownCmdLineArg", resourceCulture);
            }
        }
        
        internal static string NoFoldersFound {
            get {
                return ResourceManager.GetString("NoFoldersFound", resourceCulture);
            }
        }
        
        internal static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        internal static string AlternateStateFile {
            get {
                return ResourceManager.GetString("AlternateStateFile", resourceCulture);
            }
        }
        
        internal static string SendingEmailTo {
            get {
                return ResourceManager.GetString("SendingEmailTo", resourceCulture);
            }
        }
        
        internal static string NoRotateNotGTEMinimumFileSize {
            get {
                return ResourceManager.GetString("NoRotateNotGTEMinimumFileSize", resourceCulture);
            }
        }
        
        internal static string NoTimestampDirectives {
            get {
                return ResourceManager.GetString("NoTimestampDirectives", resourceCulture);
            }
        }
        
        internal static string GNURights {
            get {
                return ResourceManager.GetString("GNURights", resourceCulture);
            }
        }
        
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        internal static string DebugOptionSet {
            get {
                return ResourceManager.GetString("DebugOptionSet", resourceCulture);
            }
        }
        
        internal static string NewSection {
            get {
                return ResourceManager.GetString("NewSection", resourceCulture);
            }
        }
        
        internal static string DeletingFile {
            get {
                return ResourceManager.GetString("DeletingFile", resourceCulture);
            }
        }
        
        internal static string ParseConfigFile {
            get {
                return ResourceManager.GetString("ParseConfigFile", resourceCulture);
            }
        }
    }
}
